version: "3.0"

services:
  db:
    container_name: "fastapi-migrations-db"
    image: mysql:8.0
    platform: linux/x86_64
    restart: always
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my2.cnf
    env_file:
      - ./.env
    ports:
      - "23308:3306"
    command: --default-authentication-plugin=mysql_native_password
  api:
    container_name: "fastapi-migrations-api"
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    restart: always
    tty: true
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
